import {
  type Lead,
  type AdCreative,
  type FunnelStage,
  type KPIData,
  type RevenueBreakdown,
  type DashboardData,
} from "./types";
import { subDays, subMonths, format, addDays } from "date-fns";

function iso(date: Date) {
  return date.toISOString();
}

function d(daysBack: number) {
  return iso(subDays(new Date(), daysBack));
}

// ─── Mock leads ──────────────────────────────────────────────────────────────

export const MOCK_LEADS: Lead[] = [
  // ── Aftercare (booked + surgery done) ──
  {
    id: "L001",
    name: "Erik Johansen",
    email: "erik.johansen@email.no",
    phone: "+47 912 34 567",
    source: "meta",
    campaignId: "C_META_001",
    campaignName: "Hair Transplant Norway Q1",
    adSetId: "AS_META_001",
    adSetName: "Men 35-50 Oslo",
    adId: "AD_META_001",
    adName: "Before/After Carousel",
    currentBoard: "aftercare",
    currentStage: "Aftercare 6 months",
    stageHistory: [
      { board: "evaluation", stage: "New Lead", enteredAt: d(180), exitedAt: d(178), daysSpent: 2 },
      { board: "evaluation", stage: "Waiting for Images", enteredAt: d(178), exitedAt: d(173), daysSpent: 5 },
      { board: "evaluation", stage: "Images Received", enteredAt: d(173), exitedAt: d(170), daysSpent: 3 },
      { board: "evaluation", stage: "Waiting for Doctor Feedback", enteredAt: d(170), exitedAt: d(167), daysSpent: 3 },
      { board: "evaluation", stage: "Doctor Feedback Ready", enteredAt: d(167), exitedAt: d(165), daysSpent: 2 },
      { board: "sales", stage: "Not Contacted", enteredAt: d(165), exitedAt: d(163), daysSpent: 2 },
      { board: "sales", stage: "Contacted/In Dialogue", enteredAt: d(163), exitedAt: d(155), daysSpent: 8 },
      { board: "sales", stage: "Consultation Done", enteredAt: d(155), exitedAt: d(148), daysSpent: 7 },
      { board: "sales", stage: "Considering/Follow-up", enteredAt: d(148), exitedAt: d(140), daysSpent: 8 },
      { board: "sales", stage: "Ready to Book", enteredAt: d(140), exitedAt: d(135), daysSpent: 5 },
      { board: "aftercare", stage: "Booked", enteredAt: d(135), exitedAt: d(120), daysSpent: 15 },
      { board: "aftercare", stage: "Pre-Travel", enteredAt: d(120), exitedAt: d(105), daysSpent: 15 },
      { board: "aftercare", stage: "Surgery Completed", enteredAt: d(105), exitedAt: d(90), daysSpent: 15 },
      { board: "aftercare", stage: "Aftercare 3 months", enteredAt: d(90), exitedAt: d(0), daysSpent: 90 },
      { board: "aftercare", stage: "Aftercare 6 months", enteredAt: d(0), daysSpent: 0 },
    ],
    surgeryPrice: 45000,
    bookingDate: d(135),
    surgeryDate: d(105),
    createdAt: d(180),
    updatedAt: d(0),
    country: "Norway",
    grafts: 2800,
    daysInCurrentStage: 0,
  },
  {
    id: "L002",
    name: "Anders Berg",
    email: "a.berg@gmail.com",
    phone: "+47 934 56 789",
    source: "google",
    campaignId: "C_GOOGLE_001",
    campaignName: "Hair Transplant Cost Norway",
    adSetId: "AG_GOOGLE_001",
    adSetName: "Branded Search",
    adId: "AD_GOOGLE_001",
    adName: "Hair transplant cost – book free consultation",
    currentBoard: "aftercare",
    currentStage: "Aftercare 3 months",
    stageHistory: [
      { board: "evaluation", stage: "New Lead", enteredAt: d(155), exitedAt: d(153), daysSpent: 2 },
      { board: "evaluation", stage: "Waiting for Images", enteredAt: d(153), exitedAt: d(147), daysSpent: 6 },
      { board: "evaluation", stage: "Images Received", enteredAt: d(147), exitedAt: d(144), daysSpent: 3 },
      { board: "evaluation", stage: "Waiting for Doctor Feedback", enteredAt: d(144), exitedAt: d(141), daysSpent: 3 },
      { board: "evaluation", stage: "Doctor Feedback Ready", enteredAt: d(141), exitedAt: d(139), daysSpent: 2 },
      { board: "sales", stage: "Not Contacted", enteredAt: d(139), exitedAt: d(137), daysSpent: 2 },
      { board: "sales", stage: "Contacted/In Dialogue", enteredAt: d(137), exitedAt: d(128), daysSpent: 9 },
      { board: "sales", stage: "Consultation Done", enteredAt: d(128), exitedAt: d(120), daysSpent: 8 },
      { board: "sales", stage: "Considering/Follow-up", enteredAt: d(120), exitedAt: d(112), daysSpent: 8 },
      { board: "sales", stage: "Ready to Book", enteredAt: d(112), exitedAt: d(108), daysSpent: 4 },
      { board: "aftercare", stage: "Booked", enteredAt: d(108), exitedAt: d(95), daysSpent: 13 },
      { board: "aftercare", stage: "Pre-Travel", enteredAt: d(95), exitedAt: d(80), daysSpent: 15 },
      { board: "aftercare", stage: "Surgery Completed", enteredAt: d(80), exitedAt: d(65), daysSpent: 15 },
      { board: "aftercare", stage: "Aftercare 3 months", enteredAt: d(65), daysSpent: 65 },
    ],
    surgeryPrice: 38000,
    bookingDate: d(108),
    surgeryDate: d(80),
    createdAt: d(155),
    updatedAt: d(65),
    country: "Norway",
    grafts: 2200,
    daysInCurrentStage: 65,
  },
  {
    id: "L003",
    name: "Thomas Eriksen",
    email: "thomas.e@hotmail.com",
    source: "meta",
    campaignId: "C_META_002",
    campaignName: "Hair Loss Solution NOR",
    adSetId: "AS_META_002",
    adSetName: "Men 40-55 Bergen",
    adId: "AD_META_003",
    adName: "Video testimonial – Magnus",
    currentBoard: "aftercare",
    currentStage: "Surgery Completed",
    stageHistory: [
      { board: "evaluation", stage: "New Lead", enteredAt: d(120), exitedAt: d(118), daysSpent: 2 },
      { board: "evaluation", stage: "Waiting for Images", enteredAt: d(118), exitedAt: d(114), daysSpent: 4 },
      { board: "evaluation", stage: "Images Received", enteredAt: d(114), exitedAt: d(111), daysSpent: 3 },
      { board: "evaluation", stage: "Waiting for Doctor Feedback", enteredAt: d(111), exitedAt: d(108), daysSpent: 3 },
      { board: "evaluation", stage: "Doctor Feedback Ready", enteredAt: d(108), exitedAt: d(106), daysSpent: 2 },
      { board: "sales", stage: "Not Contacted", enteredAt: d(106), exitedAt: d(104), daysSpent: 2 },
      { board: "sales", stage: "Contacted/In Dialogue", enteredAt: d(104), exitedAt: d(96), daysSpent: 8 },
      { board: "sales", stage: "Consultation Done", enteredAt: d(96), exitedAt: d(88), daysSpent: 8 },
      { board: "sales", stage: "Considering/Follow-up", enteredAt: d(88), exitedAt: d(80), daysSpent: 8 },
      { board: "sales", stage: "Ready to Book", enteredAt: d(80), exitedAt: d(76), daysSpent: 4 },
      { board: "aftercare", stage: "Booked", enteredAt: d(76), exitedAt: d(60), daysSpent: 16 },
      { board: "aftercare", stage: "Pre-Travel", enteredAt: d(60), exitedAt: d(45), daysSpent: 15 },
      { board: "aftercare", stage: "Surgery Completed", enteredAt: d(45), daysSpent: 45 },
    ],
    surgeryPrice: 42000,
    bookingDate: d(76),
    surgeryDate: d(45),
    createdAt: d(120),
    updatedAt: d(45),
    country: "Norway",
    grafts: 2500,
    daysInCurrentStage: 45,
  },

  // ── Sales pipeline (active) ──
  {
    id: "L004",
    name: "Kristian Moe",
    email: "kmoe@work.no",
    phone: "+47 945 67 890",
    source: "meta",
    campaignId: "C_META_001",
    campaignName: "Hair Transplant Norway Q1",
    adSetId: "AS_META_003",
    adSetName: "Men 30-45 Nationwide",
    adId: "AD_META_002",
    adName: "Hairline restoration – results",
    currentBoard: "sales",
    currentStage: "Ready to Book",
    stageHistory: [
      { board: "evaluation", stage: "New Lead", enteredAt: d(45), exitedAt: d(43), daysSpent: 2 },
      { board: "evaluation", stage: "Waiting for Images", enteredAt: d(43), exitedAt: d(38), daysSpent: 5 },
      { board: "evaluation", stage: "Images Received", enteredAt: d(38), exitedAt: d(35), daysSpent: 3 },
      { board: "evaluation", stage: "Waiting for Doctor Feedback", enteredAt: d(35), exitedAt: d(32), daysSpent: 3 },
      { board: "evaluation", stage: "Doctor Feedback Ready", enteredAt: d(32), exitedAt: d(30), daysSpent: 2 },
      { board: "sales", stage: "Not Contacted", enteredAt: d(30), exitedAt: d(28), daysSpent: 2 },
      { board: "sales", stage: "Contacted/In Dialogue", enteredAt: d(28), exitedAt: d(20), daysSpent: 8 },
      { board: "sales", stage: "Consultation Done", enteredAt: d(20), exitedAt: d(12), daysSpent: 8 },
      { board: "sales", stage: "Considering/Follow-up", enteredAt: d(12), exitedAt: d(4), daysSpent: 8 },
      { board: "sales", stage: "Ready to Book", enteredAt: d(4), daysSpent: 4 },
    ],
    createdAt: d(45),
    updatedAt: d(4),
    country: "Norway",
    daysInCurrentStage: 4,
  },
  {
    id: "L005",
    name: "Morten Haugen",
    email: "m.haugen@gmail.com",
    source: "google",
    campaignId: "C_GOOGLE_002",
    campaignName: "Hårplanting klinikk",
    adSetId: "AG_GOOGLE_002",
    adSetName: "Non-brand search",
    adId: "AD_GOOGLE_002",
    adName: "Hårplanting – sammenlign priser",
    currentBoard: "sales",
    currentStage: "Considering/Follow-up",
    stageHistory: [
      { board: "evaluation", stage: "New Lead", enteredAt: d(40), exitedAt: d(38), daysSpent: 2 },
      { board: "evaluation", stage: "Waiting for Images", enteredAt: d(38), exitedAt: d(32), daysSpent: 6 },
      { board: "evaluation", stage: "Images Received", enteredAt: d(32), exitedAt: d(29), daysSpent: 3 },
      { board: "evaluation", stage: "Waiting for Doctor Feedback", enteredAt: d(29), exitedAt: d(26), daysSpent: 3 },
      { board: "evaluation", stage: "Doctor Feedback Ready", enteredAt: d(26), exitedAt: d(24), daysSpent: 2 },
      { board: "sales", stage: "Not Contacted", enteredAt: d(24), exitedAt: d(22), daysSpent: 2 },
      { board: "sales", stage: "Contacted/In Dialogue", enteredAt: d(22), exitedAt: d(14), daysSpent: 8 },
      { board: "sales", stage: "Consultation Done", enteredAt: d(14), exitedAt: d(6), daysSpent: 8 },
      { board: "sales", stage: "Considering/Follow-up", enteredAt: d(6), daysSpent: 6 },
    ],
    createdAt: d(40),
    updatedAt: d(6),
    country: "Norway",
    daysInCurrentStage: 6,
  },
  {
    id: "L006",
    name: "Ole Strand",
    email: "ole.strand@yahoo.no",
    source: "meta",
    campaignId: "C_META_002",
    campaignName: "Hair Loss Solution NOR",
    adSetId: "AS_META_002",
    adSetName: "Men 40-55 Bergen",
    adId: "AD_META_003",
    adName: "Video testimonial – Magnus",
    currentBoard: "sales",
    currentStage: "Considering/Follow-up",
    stageHistory: [
      { board: "evaluation", stage: "New Lead", enteredAt: d(38), exitedAt: d(36), daysSpent: 2 },
      { board: "evaluation", stage: "Waiting for Images", enteredAt: d(36), exitedAt: d(30), daysSpent: 6 },
      { board: "evaluation", stage: "Images Received", enteredAt: d(30), exitedAt: d(27), daysSpent: 3 },
      { board: "evaluation", stage: "Waiting for Doctor Feedback", enteredAt: d(27), exitedAt: d(24), daysSpent: 3 },
      { board: "evaluation", stage: "Doctor Feedback Ready", enteredAt: d(24), exitedAt: d(22), daysSpent: 2 },
      { board: "sales", stage: "Not Contacted", enteredAt: d(22), exitedAt: d(20), daysSpent: 2 },
      { board: "sales", stage: "Contacted/In Dialogue", enteredAt: d(20), exitedAt: d(12), daysSpent: 8 },
      { board: "sales", stage: "Consultation Done", enteredAt: d(12), exitedAt: d(4), daysSpent: 8 },
      { board: "sales", stage: "Considering/Follow-up", enteredAt: d(4), daysSpent: 4 },
    ],
    createdAt: d(38),
    updatedAt: d(4),
    country: "Norway",
    daysInCurrentStage: 4,
  },
  {
    id: "L007",
    name: "Per Nilsen",
    email: "per.nilsen@icloud.com",
    source: "google",
    campaignId: "C_GOOGLE_001",
    campaignName: "Hair Transplant Cost Norway",
    adSetId: "AG_GOOGLE_001",
    adSetName: "Branded Search",
    adId: "AD_GOOGLE_001",
    adName: "Hair transplant cost – book free consultation",
    currentBoard: "sales",
    currentStage: "Contacted/In Dialogue",
    stageHistory: [
      { board: "evaluation", stage: "New Lead", enteredAt: d(30), exitedAt: d(28), daysSpent: 2 },
      { board: "evaluation", stage: "Waiting for Images", enteredAt: d(28), exitedAt: d(22), daysSpent: 6 },
      { board: "evaluation", stage: "Images Received", enteredAt: d(22), exitedAt: d(19), daysSpent: 3 },
      { board: "evaluation", stage: "Waiting for Doctor Feedback", enteredAt: d(19), exitedAt: d(16), daysSpent: 3 },
      { board: "evaluation", stage: "Doctor Feedback Ready", enteredAt: d(16), exitedAt: d(14), daysSpent: 2 },
      { board: "sales", stage: "Not Contacted", enteredAt: d(14), exitedAt: d(12), daysSpent: 2 },
      { board: "sales", stage: "Contacted/In Dialogue", enteredAt: d(12), daysSpent: 12 },
    ],
    createdAt: d(30),
    updatedAt: d(12),
    country: "Norway",
    daysInCurrentStage: 12,
    isStuck: true,
  },
  {
    id: "L008",
    name: "Rune Pettersen",
    source: "meta",
    campaignId: "C_META_001",
    campaignName: "Hair Transplant Norway Q1",
    adSetId: "AS_META_001",
    adSetName: "Men 35-50 Oslo",
    adId: "AD_META_001",
    adName: "Before/After Carousel",
    currentBoard: "sales",
    currentStage: "Not Contacted",
    stageHistory: [
      { board: "evaluation", stage: "New Lead", enteredAt: d(22), exitedAt: d(20), daysSpent: 2 },
      { board: "evaluation", stage: "Waiting for Images", enteredAt: d(20), exitedAt: d(14), daysSpent: 6 },
      { board: "evaluation", stage: "Images Received", enteredAt: d(14), exitedAt: d(11), daysSpent: 3 },
      { board: "evaluation", stage: "Waiting for Doctor Feedback", enteredAt: d(11), exitedAt: d(8), daysSpent: 3 },
      { board: "evaluation", stage: "Doctor Feedback Ready", enteredAt: d(8), exitedAt: d(6), daysSpent: 2 },
      { board: "sales", stage: "Not Contacted", enteredAt: d(6), daysSpent: 6 },
    ],
    createdAt: d(22),
    updatedAt: d(6),
    country: "Norway",
    daysInCurrentStage: 6,
  },
  // Stuck leads
  {
    id: "L009",
    name: "Hallvard Dahl",
    email: "hdahl@online.no",
    source: "meta",
    campaignId: "C_META_002",
    campaignName: "Hair Loss Solution NOR",
    adSetId: "AS_META_003",
    adSetName: "Men 30-45 Nationwide",
    adId: "AD_META_004",
    adName: "Static ad – price reveal",
    currentBoard: "sales",
    currentStage: "Considering/Follow-up",
    stageHistory: [
      { board: "evaluation", stage: "New Lead", enteredAt: d(60), exitedAt: d(58), daysSpent: 2 },
      { board: "evaluation", stage: "Waiting for Images", enteredAt: d(58), exitedAt: d(52), daysSpent: 6 },
      { board: "evaluation", stage: "Images Received", enteredAt: d(52), exitedAt: d(49), daysSpent: 3 },
      { board: "evaluation", stage: "Waiting for Doctor Feedback", enteredAt: d(49), exitedAt: d(46), daysSpent: 3 },
      { board: "evaluation", stage: "Doctor Feedback Ready", enteredAt: d(46), exitedAt: d(44), daysSpent: 2 },
      { board: "sales", stage: "Not Contacted", enteredAt: d(44), exitedAt: d(42), daysSpent: 2 },
      { board: "sales", stage: "Contacted/In Dialogue", enteredAt: d(42), exitedAt: d(34), daysSpent: 8 },
      { board: "sales", stage: "Consultation Done", enteredAt: d(34), exitedAt: d(26), daysSpent: 8 },
      { board: "sales", stage: "Considering/Follow-up", enteredAt: d(26), daysSpent: 26 },
    ],
    createdAt: d(60),
    updatedAt: d(26),
    country: "Norway",
    daysInCurrentStage: 26,
    isStuck: true,
  },
  // Evaluation board leads
  {
    id: "L010",
    name: "Bjørn Lunde",
    source: "meta",
    campaignId: "C_META_001",
    campaignName: "Hair Transplant Norway Q1",
    adSetId: "AS_META_001",
    adSetName: "Men 35-50 Oslo",
    adId: "AD_META_001",
    adName: "Before/After Carousel",
    currentBoard: "evaluation",
    currentStage: "Doctor Feedback Ready",
    stageHistory: [
      { board: "evaluation", stage: "New Lead", enteredAt: d(14), exitedAt: d(12), daysSpent: 2 },
      { board: "evaluation", stage: "Waiting for Images", enteredAt: d(12), exitedAt: d(7), daysSpent: 5 },
      { board: "evaluation", stage: "Images Received", enteredAt: d(7), exitedAt: d(4), daysSpent: 3 },
      { board: "evaluation", stage: "Waiting for Doctor Feedback", enteredAt: d(4), exitedAt: d(1), daysSpent: 3 },
      { board: "evaluation", stage: "Doctor Feedback Ready", enteredAt: d(1), daysSpent: 1 },
    ],
    createdAt: d(14),
    updatedAt: d(1),
    country: "Norway",
    daysInCurrentStage: 1,
  },
  {
    id: "L011",
    name: "Svein Aasen",
    source: "google",
    campaignId: "C_GOOGLE_002",
    campaignName: "Hårplanting klinikk",
    adSetId: "AG_GOOGLE_002",
    adSetName: "Non-brand search",
    adId: "AD_GOOGLE_003",
    adName: "Hårplanting Istanbul – gratis konsultasjon",
    currentBoard: "evaluation",
    currentStage: "Waiting for Images",
    stageHistory: [
      { board: "evaluation", stage: "New Lead", enteredAt: d(8), exitedAt: d(6), daysSpent: 2 },
      { board: "evaluation", stage: "Waiting for Images", enteredAt: d(6), daysSpent: 6 },
    ],
    createdAt: d(8),
    updatedAt: d(6),
    country: "Norway",
    daysInCurrentStage: 6,
  },
  {
    id: "L012",
    name: "Lars Olsen",
    source: "meta",
    campaignId: "C_META_003",
    campaignName: "Retargeting – Visitors",
    adSetId: "AS_META_004",
    adSetName: "Website visitors 30d",
    adId: "AD_META_005",
    adName: "Retargeting – Last chance offer",
    currentBoard: "evaluation",
    currentStage: "New Lead",
    stageHistory: [
      { board: "evaluation", stage: "New Lead", enteredAt: d(2), daysSpent: 2 },
    ],
    createdAt: d(2),
    updatedAt: d(2),
    country: "Norway",
    daysInCurrentStage: 2,
  },
  {
    id: "L013",
    name: "Geir Hansen",
    source: "meta",
    campaignId: "C_META_001",
    campaignName: "Hair Transplant Norway Q1",
    adSetId: "AS_META_001",
    adSetName: "Men 35-50 Oslo",
    adId: "AD_META_002",
    adName: "Hairline restoration – results",
    currentBoard: "evaluation",
    currentStage: "Images Received",
    stageHistory: [
      { board: "evaluation", stage: "New Lead", enteredAt: d(10), exitedAt: d(8), daysSpent: 2 },
      { board: "evaluation", stage: "Waiting for Images", enteredAt: d(8), exitedAt: d(3), daysSpent: 5 },
      { board: "evaluation", stage: "Images Received", enteredAt: d(3), daysSpent: 3 },
    ],
    createdAt: d(10),
    updatedAt: d(3),
    country: "Norway",
    daysInCurrentStage: 3,
  },
  {
    id: "L014",
    name: "Nils Thorvaldsen",
    source: "google",
    campaignId: "C_GOOGLE_001",
    campaignName: "Hair Transplant Cost Norway",
    adSetId: "AG_GOOGLE_001",
    adSetName: "Branded Search",
    adId: "AD_GOOGLE_001",
    adName: "Hair transplant cost – book free consultation",
    currentBoard: "evaluation",
    currentStage: "Waiting for Doctor Feedback",
    stageHistory: [
      { board: "evaluation", stage: "New Lead", enteredAt: d(16), exitedAt: d(14), daysSpent: 2 },
      { board: "evaluation", stage: "Waiting for Images", enteredAt: d(14), exitedAt: d(9), daysSpent: 5 },
      { board: "evaluation", stage: "Images Received", enteredAt: d(9), exitedAt: d(6), daysSpent: 3 },
      { board: "evaluation", stage: "Waiting for Doctor Feedback", enteredAt: d(6), daysSpent: 6 },
    ],
    createdAt: d(16),
    updatedAt: d(6),
    country: "Norway",
    daysInCurrentStage: 6,
  },
];

// ─── Mock creatives ───────────────────────────────────────────────────────────

export const MOCK_CREATIVES: AdCreative[] = [
  {
    platform: "meta",
    campaignId: "C_META_001",
    campaignName: "Hair Transplant Norway Q1",
    adSetId: "AS_META_001",
    adSetName: "Men 35-50 Oslo",
    adId: "AD_META_001",
    adName: "Before/After Carousel",
    impressions: 48200,
    clicks: 1446,
    spend: 28500,
    leads: 38,
    bookings: 4,
    revenue: 170000,
    ctr: 3.0,
    cpc: 19.7,
    cpl: 750,
    cpb: 7125,
    roas: 5.96,
    conversionRate: 10.5,
  },
  {
    platform: "meta",
    campaignId: "C_META_001",
    campaignName: "Hair Transplant Norway Q1",
    adSetId: "AS_META_003",
    adSetName: "Men 30-45 Nationwide",
    adId: "AD_META_002",
    adName: "Hairline restoration – results",
    impressions: 35600,
    clicks: 890,
    spend: 18200,
    leads: 22,
    bookings: 2,
    revenue: 84000,
    ctr: 2.5,
    cpc: 20.4,
    cpl: 827,
    cpb: 9100,
    roas: 4.62,
    conversionRate: 9.1,
  },
  {
    platform: "meta",
    campaignId: "C_META_002",
    campaignName: "Hair Loss Solution NOR",
    adSetId: "AS_META_002",
    adSetName: "Men 40-55 Bergen",
    adId: "AD_META_003",
    adName: "Video testimonial – Magnus",
    impressions: 62100,
    clicks: 1553,
    spend: 34800,
    leads: 51,
    bookings: 5,
    revenue: 213000,
    ctr: 2.5,
    cpc: 22.4,
    cpl: 682,
    cpb: 6960,
    roas: 6.12,
    conversionRate: 9.8,
  },
  {
    platform: "meta",
    campaignId: "C_META_002",
    campaignName: "Hair Loss Solution NOR",
    adSetId: "AS_META_003",
    adSetName: "Men 30-45 Nationwide",
    adId: "AD_META_004",
    adName: "Static ad – price reveal",
    impressions: 41300,
    clicks: 785,
    spend: 15600,
    leads: 18,
    bookings: 1,
    revenue: 40000,
    ctr: 1.9,
    cpc: 19.9,
    cpl: 867,
    cpb: 15600,
    roas: 2.56,
    conversionRate: 5.6,
  },
  {
    platform: "meta",
    campaignId: "C_META_003",
    campaignName: "Retargeting – Visitors",
    adSetId: "AS_META_004",
    adSetName: "Website visitors 30d",
    adId: "AD_META_005",
    adName: "Retargeting – Last chance offer",
    impressions: 18700,
    clicks: 748,
    spend: 8900,
    leads: 14,
    bookings: 2,
    revenue: 83000,
    ctr: 4.0,
    cpc: 11.9,
    cpl: 636,
    cpb: 4450,
    roas: 9.33,
    conversionRate: 14.3,
  },
  {
    platform: "google",
    campaignId: "C_GOOGLE_001",
    campaignName: "Hair Transplant Cost Norway",
    adSetId: "AG_GOOGLE_001",
    adSetName: "Branded Search",
    adId: "AD_GOOGLE_001",
    adName: "Hair transplant cost – book free consultation",
    impressions: 9200,
    clicks: 828,
    spend: 12400,
    leads: 24,
    bookings: 3,
    revenue: 120000,
    ctr: 9.0,
    cpc: 15.0,
    cpl: 517,
    cpb: 4133,
    roas: 9.68,
    conversionRate: 12.5,
  },
  {
    platform: "google",
    campaignId: "C_GOOGLE_002",
    campaignName: "Hårplanting klinikk",
    adSetId: "AG_GOOGLE_002",
    adSetName: "Non-brand search",
    adId: "AD_GOOGLE_002",
    adName: "Hårplanting – sammenlign priser",
    impressions: 14800,
    clicks: 1036,
    spend: 19200,
    leads: 19,
    bookings: 2,
    revenue: 82000,
    ctr: 7.0,
    cpc: 18.5,
    cpl: 1011,
    cpb: 9600,
    roas: 4.27,
    conversionRate: 10.5,
  },
  {
    platform: "google",
    campaignId: "C_GOOGLE_002",
    campaignName: "Hårplanting klinikk",
    adSetId: "AG_GOOGLE_002",
    adSetName: "Non-brand search",
    adId: "AD_GOOGLE_003",
    adName: "Hårplanting Istanbul – gratis konsultasjon",
    impressions: 11500,
    clicks: 806,
    spend: 14700,
    leads: 15,
    bookings: 1,
    revenue: 38000,
    ctr: 7.0,
    cpc: 18.2,
    cpl: 980,
    cpb: 14700,
    roas: 2.59,
    conversionRate: 6.7,
  },
];

// ─── Funnel stages ────────────────────────────────────────────────────────────

export const MOCK_FUNNEL: FunnelStage[] = [
  { board: "evaluation", stage: "New Lead", order: 1, count: 201, cumulativeDropoff: 0, stageDropoff: 0, avgDaysInStage: 2 },
  { board: "evaluation", stage: "Waiting for Images", order: 2, count: 185, cumulativeDropoff: 8.0, stageDropoff: 8.0, avgDaysInStage: 5.4 },
  { board: "evaluation", stage: "Images Received", order: 3, count: 162, cumulativeDropoff: 19.4, stageDropoff: 12.4, avgDaysInStage: 3.1 },
  { board: "evaluation", stage: "Waiting for Doctor Feedback", order: 4, count: 148, cumulativeDropoff: 26.4, stageDropoff: 8.6, avgDaysInStage: 2.8 },
  { board: "evaluation", stage: "Doctor Feedback Ready", order: 5, count: 140, cumulativeDropoff: 30.3, stageDropoff: 5.4, avgDaysInStage: 1.9 },
  { board: "sales", stage: "Not Contacted", order: 6, count: 126, cumulativeDropoff: 37.3, stageDropoff: 10.0, avgDaysInStage: 2.1 },
  { board: "sales", stage: "Contacted/In Dialogue", order: 7, count: 112, cumulativeDropoff: 44.3, stageDropoff: 11.1, avgDaysInStage: 8.6 },
  { board: "sales", stage: "Consultation Done", order: 8, count: 89, cumulativeDropoff: 55.7, stageDropoff: 20.5, avgDaysInStage: 7.9 },
  { board: "sales", stage: "Considering/Follow-up", order: 9, count: 72, cumulativeDropoff: 64.2, stageDropoff: 19.1, avgDaysInStage: 11.2 },
  { board: "sales", stage: "Ready to Book", order: 10, count: 48, cumulativeDropoff: 76.1, stageDropoff: 33.3, avgDaysInStage: 5.3 },
  { board: "aftercare", stage: "Booked", order: 11, count: 38, cumulativeDropoff: 81.1, stageDropoff: 20.8, avgDaysInStage: 14.8 },
  { board: "aftercare", stage: "Pre-Travel", order: 12, count: 31, cumulativeDropoff: 84.6, stageDropoff: 18.4, avgDaysInStage: 14.2 },
  { board: "aftercare", stage: "Surgery Completed", order: 13, count: 28, cumulativeDropoff: 86.1, stageDropoff: 9.7, avgDaysInStage: 0 },
  { board: "aftercare", stage: "Aftercare 3 months", order: 14, count: 22, cumulativeDropoff: 89.1, stageDropoff: 21.4, avgDaysInStage: 90 },
  { board: "aftercare", stage: "Aftercare 6 months", order: 15, count: 14, cumulativeDropoff: 93.0, stageDropoff: 36.4, avgDaysInStage: 90 },
  { board: "aftercare", stage: "Aftercare 9 months", order: 16, count: 9, cumulativeDropoff: 95.5, stageDropoff: 35.7, avgDaysInStage: 90 },
  { board: "aftercare", stage: "Aftercare 12 months", order: 17, count: 5, cumulativeDropoff: 97.5, stageDropoff: 44.4, avgDaysInStage: 90 },
];

// ─── KPIs ─────────────────────────────────────────────────────────────────────

export const MOCK_KPIS: KPIData = {
  totalLeads: 201,
  totalBookings: 38,
  overallConversionRate: 18.9,
  leadToSalesRate: 62.7,
  salesToBookingRate: 30.2,
  avgDaysLeadToBooked: 47,
  totalRevenue: 1596000,
  totalAdSpend: 152300,
  roas: 10.48,
  socoFee: 164600, // 5000 + 10% * 1596000
  costPerLead: 757,
  costPerBooking: 4008,
  activeLeads: 163,
  stuckLeads: 8,
  deltaLeads: 12,
  deltaBookings: 3,
  deltaRoas: 1.2,
};

// ─── Revenue breakdown ────────────────────────────────────────────────────────

export const MOCK_REVENUE: RevenueBreakdown[] = [
  { month: "2024-01", label: "Jan", bookings: 2, revenue: 84000, adSpend: 18200, roas: 4.62, socoFee: 13400, profit: 70600 },
  { month: "2024-02", label: "Feb", bookings: 3, revenue: 126000, adSpend: 22400, roas: 5.63, socoFee: 17600, profit: 108400 },
  { month: "2024-03", label: "Mar", bookings: 5, revenue: 210000, adSpend: 28600, roas: 7.34, socoFee: 26000, profit: 184000 },
  { month: "2024-04", label: "Apr", bookings: 4, revenue: 168000, adSpend: 24800, roas: 6.77, socoFee: 21800, profit: 146200 },
  { month: "2024-05", label: "Mai", bookings: 6, revenue: 252000, adSpend: 31200, roas: 8.08, socoFee: 30200, profit: 221800 },
  { month: "2024-06", label: "Jun", bookings: 7, revenue: 294000, adSpend: 34600, roas: 8.50, socoFee: 34400, profit: 259600 },
  { month: "2024-07", label: "Jul", bookings: 4, revenue: 168000, adSpend: 28900, roas: 5.81, socoFee: 21800, profit: 146200 },
  { month: "2024-08", label: "Aug", bookings: 7, revenue: 294000, adSpend: 36200, roas: 8.12, socoFee: 34400, profit: 259600 },
];

// ─── Full mock dashboard ──────────────────────────────────────────────────────

export function getMockDashboardData(): DashboardData {
  return {
    kpis: MOCK_KPIS,
    funnel: MOCK_FUNNEL,
    creatives: MOCK_CREATIVES,
    leads: MOCK_LEADS,
    revenue: MOCK_REVENUE,
    dataSource: "mock",
    lastUpdated: new Date().toISOString(),
    apiStatus: {
      monday: "unconfigured",
      meta: "unconfigured",
      google: "unconfigured",
    },
  };
}
